site_name: SGP-Tools
site_author: Kalvik Jakkala
site_url: https://SGP-Tools.com
repo_name: sgp-tools

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.png
  logo: assets/SGP-Tools.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom

  icon:
    repo: fontawesome/brands/github

  features:
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate 
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.indexes 
    - content.code.copy

plugins:
  - search
  - offline
  - mkdocs-jupyter
  - mkdocstrings

nav:
  - Home: index.md
  - API Docs: 
    - Overview: api/index.md
    - Core:
      - api/core/index.md
      - AugmentedGPR: api/core/augmented_gpr.md
      - AugmentedSGPR: api/core/augmented_sgpr.md
      - OSGPR: api/core/osgpr.md
      - Transformations: api/core/transformations.md
    - Kernels:
      - api/kernels/index.md
      - Attentive Kernel: api/kernels/attentive_kernel.md
      - Neural Kernel: api/kernels/neural_kernel.md
      - Neural Network: api/kernels/neural_network.md
    - Methods:
      - api/methods/index.md
      - ContinuousSGP: api/methods/continuous_sgp.md
      - GreedySGP: api/methods/greedy_sgp.md
      - GreedyObjective: api/methods/greedy_objective.md
      - BayesianOpt: api/methods/bayesian_opt.md
      - CMA: api/methods/cma.md
      - Method: api/methods/method.md
    - Objectives:
      - api/objectives/index.md
      - Objective: api/objectives/objective.md
      - MI: api/objectives/mi.md
      - SLogMI: api/objectives/slog_mi.md
    - Utils:
      - api/utils/index.md
      - Data: api/utils/data.md
      - GPflow: api/utils/gpflow.md
      - Metrics: api/utils/metrics.md
      - Misc: api/utils/misc.md
      - TSP: api/utils/tsp.md
  - Tutorials:
      - tutorials/index.md
      - IPP-2D: tutorials/IPP-2D.ipynb
      - Non-Stationary Kernels: tutorials/non_stationary_kernels.ipynb

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-Z2TVV3MF1S

repo_url: https://github.com/itskalvik/sgp-tools

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js