site_name: SGP-Tools
site_author: Kalvik Jakkala
site_url: https://www.itskalvik.com/sgp-tools/

theme:
  name: "material"
  custom_dir: overrides
  favicon: assets/favicon.png
  logo: assets/SGP-Tools.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom

  icon:
    repo: fontawesome/brands/github

  features:
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate 
    - toc.follow
    - navigation.top
    - navigation.tabs.sticky
    - navigation.tabs
    - navigation.sections
    - navigation.indexes 
    - content.code.copy

plugins:
  - mkdocstrings
  - search
  - offline
  - mkdocs-jupyter

nav:
  - index.md
  - API Documentation:
    - models:    
      - "": api/models/index.md 
      - api/models/Bayesian-Optimization.md
      - api/models/Genetic-Algorithm.md
      - api/models/Continuous-SGP.md
      - api/models/Greedy-MI.md
      - api/models/Greedy-SGP.md
    - models.core:
      - "": api/models/core/index.md
      - api/models/core/AugmentedGPR.md
      - api/models/core/AugmentedSGPR.md
      - api/models/core/OSGPR.md
      - api/models/core/Transformations.md
    - kernels: 
      - "": api/kernels/index.md
      - api/kernels/Neural-Kernel.md
      - api/kernels/Attentive-Kernel.md
      - api/kernels/Neural-Network.md
    - utils:
      - "": api/utils/index.md
      - api/utils/Data.md
      - api/utils/GPflow.md
      - api/utils/Metrics.md
      - api/utils//Misc.md
      - api/utils/TSP.md
  - ROS 2:
    - "ROS 2": ros2.md
  - Docker:
    - "Docker": docker.md
  - BlueOS:
    - "BlueOS": blueos.md
  - Examples:
      - examples/AIPP_non_point_FoV.ipynb  
      - examples/IPP.ipynb  
      - examples/Baselines.ipynb  
      - examples/non_point_FoV.ipynb
      - examples/non_stationary_kernels.ipynb  
      - examples/obstacles.ipynb

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: G-Z2TVV3MF1S

repo_url: https://github.com/itskalvik/SGP-Tools

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg