site_name: SGP-Tools

theme:
  name: "material"
  logo: assets/SGP-Tools.png
  palette:
    primary: custom
  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings

nav:
  - index.md

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/itskalvik/SGP-Tools
