site_name: SGP-Tools
site_author: Kalvik Jakkala

theme:
  name: "material"
  custom_dir: overrides

  logo: assets/SGP-Tools.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: custom
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: custom
      accent: custom

  icon:
    repo: fontawesome/brands/github

plugins:
  - mkdocstrings

nav:
  - index.md
  - API-reference.md

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/itskalvik/SGP-Tools
